Enable support for HT Mode

diff --git a/packages/meshkit/bin/meshkitd b/packages/meshkit/bin/meshkitd
--- a/packages/meshkit/bin/meshkitd
+++ b/packages/meshkit/bin/meshkitd
@@ -130,7 +130,10 @@ if [ "${MESH_IF}" != "" ]; then
 	sleep 1
 	ifconfig -a | grep ${MESH_IF} &> /dev/null || die "No such iface ${MESH_IF}"
 	iw dev ${MESH_IF} interface add mesh0 type mesh || die "Failed to add mesh interface"
-	iw dev mesh0 set channel ${MESH_CHANNEL} || die "Failed to change to mesh channel"
+	if [ "${MESH_HTMODE}" != "HT20" -a "${MESH_HTMODE}" != "HT40+" -a "${MESH_HTMODE}" != "HT40-" ]; then
+		MESH_HTMODE=""
+	fi
+	iw dev mesh0 set channel ${MESH_CHANNEL} ${MESH_HTMODE}|| die "Failed to change to mesh channel"
 	ip link set dev mesh0 up || die "Failed to bring up mesh interface"
 	if [ "${MESH_PASSWORD}" = "" ]; then
 		iw dev mesh0 mesh join ${MESH_ID} || die "Failed to join mesh"
@@ -138,6 +141,7 @@ if [ "${MESH_IF}" != "" ]; then
 		# Set up secure mesh.  Note that first we must create various config
 		# files required by authsae
 		mkdir -p /var/run/authsae || die "Failed to create authsae config dir"
+		[ "${MESH_HTMODE}" == "" ] && MESH_HTMODE="none"
 		echo "$(cat <<EOF
 authsae:
 {
@@ -159,6 +163,7 @@ authsae:
     mediaopt=1;
     band="${MESH_BAND}";
     channel=${MESH_CHANNEL};
+    htmode="${MESH_HTMODE}";
   };
 };
 EOF
