Launch hostapd on mesh gates.

diff --git a/packages/meshkit/bin/meshkitd b/packages/meshkit/bin/meshkitd
--- a/packages/meshkit/bin/meshkitd
+++ b/packages/meshkit/bin/meshkitd
@@ -67,11 +67,13 @@ function bridge_ifaces {
 	_BRIDGE_IF=${1}
 	_IF1=${2}
 	_IF2=${3}
-	log "Bridging ${_IF1} and ${_IF2} interfaces."
+	_IF3=${4}
+	log "Bridging ${_IF1} ${_IF2} ${_IF3} interfaces."
 	ip addr flush dev ${_IF1} || die "Failed to flush the interface ${_IF1}"
 	ip addr flush dev ${_IF2} || die "Failed to flush the interface ${_IF2}"
+	ip addr flush dev ${_IF3} &> /dev/null
 	brctl addbr ${_BRIDGE_IF} || die "Failed to create the brigde interface ${_BRIDGE_IF}"
-	brctl addif ${_BRIDGE_IF} ${_IF1} ${_IF2} || die "Failed to add ${_IF1} and ${_IF2} to ${_BRIDGE_IF}"
+	brctl addif ${_BRIDGE_IF} ${_IF1} ${_IF2} ${_IF3} || die "Failed to add ${_IF1} ${_IF2} ${_IF3} to ${_BRIDGE_IF}"
 	_MAC=`ifconfig ${_IF1} | grep HWaddr | awk '{print$5}'`
 	ip link set ${_BRIDGE_IF} address ${_MAC} || die "Failed to set the MAC address of ${_IF1} to ${_BRIDGE_IF}"
 	ip link set dev ${_BRIDGE_IF} up
@@ -176,9 +178,9 @@ EOF
 	log "Mesh deployed"
 fi
 
-# If the node is a MESH GATE, it will bridge mesh0 with eth0. If not, with wlan1
+# If the node is a MESH GATE, it will bridge mesh0 with eth0 and wlan1. If not, just with wlan1
 if [ "${MESH_GATE}" == "yes" ]; then
-	BRGD_IF=eth0
+	BRGD_IF="eth0 wlan1"
 	iw mesh0 set mesh_param mesh_hwmp_rootmode=1
 	iw mesh0 set mesh_param mesh_gate_announcements=1
 else
@@ -203,19 +205,17 @@ fi
 if [ "${INFRA_IF}" != "" ]; then
 	ip link set dev ${INFRA_IF} down || die "failed to bring down infra interface ${INFRA_IF}"
 
-	if [ "${MESH_GATE}" != "yes" ]; then
-		# prepare the config file
-		HOSTAP_CONF=/etc/meshkit/hostapd.default.conf
-		[ -e /etc/meshkit/hostapd.conf ] && HOSTAP_CONF=/etc/meshkit/hostapd.conf
-		[ -e ${HOSTAP_CONF} ] || die "${HOSTAP_CONF} file does not exist"
-		mkdir -p /var/run/hostapd/
-		rm -f /var/run/hostapd/hostapd.conf
-		while read l; do
-			L=`eval echo ${l}`
-			[ "${L}" != "" ] && echo ${L} >> /var/run/hostapd/hostapd.conf
-		done < ${HOSTAP_CONF}
-		hostapd -B /var/run/hostapd/hostapd.conf || die "Failed to launch hostapd"
-	fi
+	# prepare the config file
+	HOSTAP_CONF=/etc/meshkit/hostapd.default.conf
+	[ -e /etc/meshkit/hostapd.conf ] && HOSTAP_CONF=/etc/meshkit/hostapd.conf
+	[ -e ${HOSTAP_CONF} ] || die "${HOSTAP_CONF} file does not exist"
+	mkdir -p /var/run/hostapd/
+	rm -f /var/run/hostapd/hostapd.conf
+	while read l; do
+		L=`eval echo ${l}`
+		[ "${L}" != "" ] && echo ${L} >> /var/run/hostapd/hostapd.conf
+	done < ${HOSTAP_CONF}
+	hostapd -B /var/run/hostapd/hostapd.conf || die "Failed to launch hostapd"
 
 	bridge_ifaces br0 mesh0 ${BRGD_IF}
 	sleep 10
